services:

  datomic-storage:
    image: postgres:16.4-bookworm
    environment:
      POSTGRES_DB: my-datomic-storage
      POSTGRES_USER: datomic-user
      POSTGRES_PASSWORD: unsafe
    ports:
      - '5432:5432'

  datomic-transactor:
    build: ./docker/transactor
    environment:
      BOOT_CONFIG_EDN: /usr/config/postgresql/config.edn
    volumes:
      - ./config:/usr/config
    ports:
      - '4334:4334'

  datomic-peer-server:
    build: ./docker/peer-server
    links:
      - datomic-storage
    environment:
      PORT: 8998
      DATOMIC_DATABASE: my-datomic-database
      DATOMIC_STORAGE_URI: datomic:sql://my-datomic-database?jdbc:postgresql://datomic-storage:5432/my-datomic-storage?user=datomic-user&password=unsafe
      DATOMIC_ACCESS_KEY: unsafe-key
      DATOMIC_SECRET: unsafe-secret
    ports:
      - 8998:8998

  datomic-console:
    build: ./docker/console
    links:
      - datomic-storage
    environment:
      DB_URI: datomic:sql://?jdbc:postgresql://datomic-storage:5432/my-datomic-storage?user=datomic-user&password=unsafe
    ports:
      - '8080:8080'

  datomic-tools:
    build: ./docker/tools
    links:
      - datomic-storage
      - datomic-peer-server
